version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:15.3-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vikv/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    image: vikv/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: vikv/taski_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
